import { TrunkRoute, Review, User } from './types';

export const SERBIAN_CITIES = [
  "Beograd", "Novi Sad", "Niš", "Kragujevac", "Subotica",
  "Zrenjanin", "Pančevo", "Čačak", "Kraljevo", "Novi Pazar",
  "Smederevo", "Leskovac", "Užice", "Vranje", "Šabac",
  "Valjevo", "Kruševac", "Sombor", "Požarevac", "Pirot",
];

export const DEMO_USERS: User[] = [
  {
    id: 'driver-1', name: 'Marko Petrović', email: 'marko@email.com', age: 32, city: 'Beograd',
    bio: 'Putujem redovno između Beograda i Novog Sada. Pouzdan i tačan vozač sa 3 godine iskustva na platformi.',
    verified: true, deliveryCount: 87, avgResponseTime: '3 min',
  },
  {
    id: 'driver-2', name: 'Ana Jovanović', email: 'ana@email.com', age: 28, city: 'Niš',
    bio: 'Studentkinja koja često putuje. Uvek imam mesta u gepeku za vaše pakete!',
    verified: true, deliveryCount: 42, avgResponseTime: '5 min',
  },
  {
    id: 'driver-3', name: 'Stefan Nikolić', email: 'stefan@email.com', age: 35, city: 'Kragujevac',
    bio: 'Profesionalni vozač, putujem kroz celu Srbiju. Bezbedna i brza dostava garantovana.',
    verified: true, deliveryCount: 124, avgResponseTime: '2 min',
  },
  {
    id: 'driver-4', name: 'Jelena Đorđević', email: 'jelena@email.com', age: 26, city: 'Novi Sad',
    bio: 'Volim da pomognem ljudima da pošalju svoje pakete. Uvek nasmejana i komunikativna!',
    verified: false, deliveryCount: 31, avgResponseTime: '8 min',
  },
  {
    id: 'driver-5', name: 'Nikola Stojanović', email: 'nikola@email.com', age: 41, city: 'Subotica',
    bio: 'Iskusan vozač sa čistim dosadašnjim ocenama. Vaši paketi su u sigurnim rukama.',
    verified: true, deliveryCount: 203, avgResponseTime: '4 min',
  },
  {
    id: 'driver-6', name: 'Milica Ilić', email: 'milica@email.com', age: 30, city: 'Čačak',
    bio: 'Redovno putujem na relaciji Čačak–Beograd i rado prenosim pakete.',
    verified: true, deliveryCount: 56, avgResponseTime: '6 min',
  },
  {
    id: 'driver-7', name: 'Đorđe Milanović', email: 'djordje@email.com', age: 38, city: 'Kraljevo',
    bio: 'Preduzimač koji putuje širom Srbije. Koristim TrunkShare od prvog dana.',
    verified: true, deliveryCount: 178, avgResponseTime: '3 min',
  },
  {
    id: 'driver-8', name: 'Ivana Popović', email: 'ivana@email.com', age: 24, city: 'Zrenjanin',
    bio: 'Nova na platformi ali veoma posvećena! Svaki paket tretiram kao da je moj.',
    verified: false, deliveryCount: 12, avgResponseTime: '10 min',
  },
  {
    id: 'driver-9', name: 'Aleksandar Pavlović', email: 'aleksandar@email.com', age: 45, city: 'Valjevo',
    bio: 'Kamionski vozač u penziji. Sada uživam da pomažem ljudima sa manjim paketima.',
    verified: true, deliveryCount: 95, avgResponseTime: '7 min',
  },
  {
    id: 'driver-10', name: 'Tamara Milošević', email: 'tamara@email.com', age: 29, city: 'Užice',
    bio: 'Marketing menadžerka koja putuje skoro svaki dan. Uvek imam mesta za paket ili dva.',
    verified: true, deliveryCount: 67, avgResponseTime: '4 min',
  },
];

export const DEMO_ROUTES: TrunkRoute[] = [
  // === MART 1 ===
  { id: 'r-01', driverId: 'driver-1', driverName: 'Marko Petrović', driverVerified: true, from: 'Beograd', to: 'Novi Sad', date: '2026-03-01', time: '08:00', availableSlots: 3 },
  { id: 'r-02', driverId: 'driver-5', driverName: 'Nikola Stojanović', driverVerified: true, from: 'Subotica', to: 'Beograd', date: '2026-03-01', time: '06:30', availableSlots: 5 },
  { id: 'r-03', driverId: 'driver-9', driverName: 'Aleksandar Pavlović', driverVerified: true, from: 'Valjevo', to: 'Beograd', date: '2026-03-01', time: '08:00', availableSlots: 3 },
  { id: 'r-04', driverId: 'driver-7', driverName: 'Đorđe Milanović', driverVerified: true, from: 'Kraljevo', to: 'Beograd', date: '2026-03-01', time: '16:00', availableSlots: 2 },
  { id: 'r-05', driverId: 'driver-3', driverName: 'Stefan Nikolić', driverVerified: true, from: 'Kragujevac', to: 'Beograd', date: '2026-03-01', time: '07:00', availableSlots: 4 },
  { id: 'r-06', driverId: 'driver-6', driverName: 'Milica Ilić', driverVerified: true, from: 'Čačak', to: 'Beograd', date: '2026-03-01', time: '09:00', availableSlots: 2 },
  { id: 'r-07', driverId: 'driver-2', driverName: 'Ana Jovanović', driverVerified: true, from: 'Niš', to: 'Kragujevac', date: '2026-03-01', time: '11:00', availableSlots: 3 },
  { id: 'r-08', driverId: 'driver-10', driverName: 'Tamara Milošević', driverVerified: true, from: 'Užice', to: 'Čačak', date: '2026-03-01', time: '10:00', availableSlots: 2 },
  { id: 'r-09', driverId: 'driver-4', driverName: 'Jelena Đorđević', from: 'Novi Sad', to: 'Zrenjanin', date: '2026-03-01', time: '14:00', availableSlots: 3 },
  { id: 'r-10', driverId: 'driver-8', driverName: 'Ivana Popović', from: 'Zrenjanin', to: 'Pančevo', date: '2026-03-01', time: '12:00', availableSlots: 1 },
  { id: 'r-11', driverId: 'driver-1', driverName: 'Marko Petrović', driverVerified: true, from: 'Pančevo', to: 'Beograd', date: '2026-03-01', time: '15:00', availableSlots: 4 },
  { id: 'r-12', driverId: 'driver-5', driverName: 'Nikola Stojanović', driverVerified: true, from: 'Smederevo', to: 'Beograd', date: '2026-03-01', time: '07:30', availableSlots: 3 },
  // === MART 2 ===
  { id: 'r-13', driverId: 'driver-2', driverName: 'Ana Jovanović', driverVerified: true, from: 'Niš', to: 'Beograd', date: '2026-03-02', time: '10:30', availableSlots: 2 },
  { id: 'r-14', driverId: 'driver-6', driverName: 'Milica Ilić', driverVerified: true, from: 'Čačak', to: 'Beograd', date: '2026-03-02', time: '07:00', availableSlots: 2 },
  { id: 'r-15', driverId: 'driver-10', driverName: 'Tamara Milošević', driverVerified: true, from: 'Užice', to: 'Beograd', date: '2026-03-02', time: '06:00', availableSlots: 2 },
  { id: 'r-16', driverId: 'driver-1', driverName: 'Marko Petrović', driverVerified: true, from: 'Beograd', to: 'Zrenjanin', date: '2026-03-02', time: '09:00', availableSlots: 4 },
  { id: 'r-17', driverId: 'driver-3', driverName: 'Stefan Nikolić', driverVerified: true, from: 'Beograd', to: 'Niš', date: '2026-03-02', time: '06:00', availableSlots: 3 },
  { id: 'r-18', driverId: 'driver-7', driverName: 'Đorđe Milanović', driverVerified: true, from: 'Beograd', to: 'Kraljevo', date: '2026-03-02', time: '08:30', availableSlots: 2 },
  { id: 'r-19', driverId: 'driver-9', driverName: 'Aleksandar Pavlović', driverVerified: true, from: 'Beograd', to: 'Valjevo', date: '2026-03-02', time: '11:00', availableSlots: 3 },
  { id: 'r-20', driverId: 'driver-4', driverName: 'Jelena Đorđević', from: 'Novi Sad', to: 'Subotica', date: '2026-03-02', time: '13:00', availableSlots: 2 },
  { id: 'r-21', driverId: 'driver-8', driverName: 'Ivana Popović', from: 'Pančevo', to: 'Smederevo', date: '2026-03-02', time: '10:00', availableSlots: 1 },
  { id: 'r-22', driverId: 'driver-5', driverName: 'Nikola Stojanović', driverVerified: true, from: 'Kruševac', to: 'Niš', date: '2026-03-02', time: '14:00', availableSlots: 3 },
  { id: 'r-23', driverId: 'driver-2', driverName: 'Ana Jovanović', driverVerified: true, from: 'Leskovac', to: 'Niš', date: '2026-03-02', time: '08:00', availableSlots: 2 },
  { id: 'r-24', driverId: 'driver-7', driverName: 'Đorđe Milanović', driverVerified: true, from: 'Novi Pazar', to: 'Kraljevo', date: '2026-03-02', time: '15:00', availableSlots: 2 },
  // === MART 3 ===
  { id: 'r-25', driverId: 'driver-3', driverName: 'Stefan Nikolić', driverVerified: true, from: 'Kragujevac', to: 'Čačak', date: '2026-03-03', time: '14:00', availableSlots: 1 },
  { id: 'r-26', driverId: 'driver-7', driverName: 'Đorđe Milanović', driverVerified: true, from: 'Kraljevo', to: 'Niš', date: '2026-03-03', time: '11:00', availableSlots: 3 },
  { id: 'r-27', driverId: 'driver-8', driverName: 'Ivana Popović', from: 'Zrenjanin', to: 'Novi Sad', date: '2026-03-03', time: '15:00', availableSlots: 1 },
  { id: 'r-28', driverId: 'driver-4', driverName: 'Jelena Đorđević', from: 'Novi Sad', to: 'Beograd', date: '2026-03-03', time: '10:00', availableSlots: 3 },
  { id: 'r-29', driverId: 'driver-5', driverName: 'Nikola Stojanović', driverVerified: true, from: 'Beograd', to: 'Niš', date: '2026-03-03', time: '07:30', availableSlots: 4 },
  { id: 'r-30', driverId: 'driver-1', driverName: 'Marko Petrović', driverVerified: true, from: 'Beograd', to: 'Subotica', date: '2026-03-03', time: '08:00', availableSlots: 3 },
  { id: 'r-31', driverId: 'driver-6', driverName: 'Milica Ilić', driverVerified: true, from: 'Beograd', to: 'Čačak', date: '2026-03-03', time: '09:00', availableSlots: 2 },
  { id: 'r-32', driverId: 'driver-9', driverName: 'Aleksandar Pavlović', driverVerified: true, from: 'Šabac', to: 'Beograd', date: '2026-03-03', time: '06:30', availableSlots: 4 },
  { id: 'r-33', driverId: 'driver-10', driverName: 'Tamara Milošević', driverVerified: true, from: 'Požarevac', to: 'Beograd', date: '2026-03-03', time: '07:00', availableSlots: 2 },
  { id: 'r-34', driverId: 'driver-2', driverName: 'Ana Jovanović', driverVerified: true, from: 'Vranje', to: 'Niš', date: '2026-03-03', time: '12:00', availableSlots: 3 },
  { id: 'r-35', driverId: 'driver-3', driverName: 'Stefan Nikolić', driverVerified: true, from: 'Pirot', to: 'Niš', date: '2026-03-03', time: '16:00', availableSlots: 2 },
  // === MART 4 ===
  { id: 'r-36', driverId: 'driver-4', driverName: 'Jelena Đorđević', from: 'Beograd', to: 'Niš', date: '2026-03-04', time: '07:00', availableSlots: 2 },
  { id: 'r-37', driverId: 'driver-3', driverName: 'Stefan Nikolić', driverVerified: true, from: 'Beograd', to: 'Kragujevac', date: '2026-03-04', time: '09:30', availableSlots: 2 },
  { id: 'r-38', driverId: 'driver-6', driverName: 'Milica Ilić', driverVerified: true, from: 'Beograd', to: 'Čačak', date: '2026-03-04', time: '13:00', availableSlots: 2 },
  { id: 'r-39', driverId: 'driver-1', driverName: 'Marko Petrović', driverVerified: true, from: 'Beograd', to: 'Novi Sad', date: '2026-03-04', time: '17:00', availableSlots: 2 },
  { id: 'r-40', driverId: 'driver-9', driverName: 'Aleksandar Pavlović', driverVerified: true, from: 'Beograd', to: 'Valjevo', date: '2026-03-04', time: '11:00', availableSlots: 3 },
  { id: 'r-41', driverId: 'driver-5', driverName: 'Nikola Stojanović', driverVerified: true, from: 'Beograd', to: 'Subotica', date: '2026-03-04', time: '06:00', availableSlots: 5 },
  { id: 'r-42', driverId: 'driver-10', driverName: 'Tamara Milošević', driverVerified: true, from: 'Beograd', to: 'Užice', date: '2026-03-04', time: '08:00', availableSlots: 2 },
  { id: 'r-43', driverId: 'driver-7', driverName: 'Đorđe Milanović', driverVerified: true, from: 'Niš', to: 'Leskovac', date: '2026-03-04', time: '10:00', availableSlots: 3 },
  { id: 'r-44', driverId: 'driver-2', driverName: 'Ana Jovanović', driverVerified: true, from: 'Novi Sad', to: 'Sombor', date: '2026-03-04', time: '14:00', availableSlots: 2 },
  { id: 'r-45', driverId: 'driver-8', driverName: 'Ivana Popović', from: 'Kruševac', to: 'Kragujevac', date: '2026-03-04', time: '12:00', availableSlots: 1 },
  { id: 'r-46', driverId: 'driver-1', driverName: 'Marko Petrović', driverVerified: true, from: 'Smederevo', to: 'Požarevac', date: '2026-03-04', time: '15:30', availableSlots: 3 },
  // === MART 5 ===
  { id: 'r-47', driverId: 'driver-1', driverName: 'Marko Petrović', driverVerified: true, from: 'Novi Sad', to: 'Subotica', date: '2026-03-05', time: '09:00', availableSlots: 4 },
  { id: 'r-48', driverId: 'driver-5', driverName: 'Nikola Stojanović', driverVerified: true, from: 'Beograd', to: 'Subotica', date: '2026-03-05', time: '12:00', availableSlots: 3 },
  { id: 'r-49', driverId: 'driver-2', driverName: 'Ana Jovanović', driverVerified: true, from: 'Beograd', to: 'Niš', date: '2026-03-05', time: '08:30', availableSlots: 3 },
  { id: 'r-50', driverId: 'driver-10', driverName: 'Tamara Milošević', driverVerified: true, from: 'Beograd', to: 'Užice', date: '2026-03-05', time: '14:00', availableSlots: 2 },
  { id: 'r-51', driverId: 'driver-7', driverName: 'Đorđe Milanović', driverVerified: true, from: 'Niš', to: 'Kragujevac', date: '2026-03-05', time: '10:00', availableSlots: 3 },
  { id: 'r-52', driverId: 'driver-3', driverName: 'Stefan Nikolić', driverVerified: true, from: 'Beograd', to: 'Kraljevo', date: '2026-03-05', time: '07:00', availableSlots: 4 },
  { id: 'r-53', driverId: 'driver-4', driverName: 'Jelena Đorđević', from: 'Šabac', to: 'Valjevo', date: '2026-03-05', time: '11:00', availableSlots: 2 },
  { id: 'r-54', driverId: 'driver-6', driverName: 'Milica Ilić', driverVerified: true, from: 'Sombor', to: 'Subotica', date: '2026-03-05', time: '13:30', availableSlots: 2 },
  { id: 'r-55', driverId: 'driver-9', driverName: 'Aleksandar Pavlović', driverVerified: true, from: 'Pančevo', to: 'Smederevo', date: '2026-03-05', time: '16:00', availableSlots: 3 },
  { id: 'r-56', driverId: 'driver-8', driverName: 'Ivana Popović', from: 'Novi Pazar', to: 'Kraljevo', date: '2026-03-05', time: '09:30', availableSlots: 1 },
  // === MART 6 ===
  { id: 'r-57', driverId: 'driver-3', driverName: 'Stefan Nikolić', driverVerified: true, from: 'Beograd', to: 'Niš', date: '2026-03-06', time: '06:00', availableSlots: 3 },
  { id: 'r-58', driverId: 'driver-6', driverName: 'Milica Ilić', driverVerified: true, from: 'Čačak', to: 'Kraljevo', date: '2026-03-06', time: '09:00', availableSlots: 2 },
  { id: 'r-59', driverId: 'driver-1', driverName: 'Marko Petrović', driverVerified: true, from: 'Beograd', to: 'Novi Sad', date: '2026-03-06', time: '07:00', availableSlots: 4 },
  { id: 'r-60', driverId: 'driver-5', driverName: 'Nikola Stojanović', driverVerified: true, from: 'Beograd', to: 'Kragujevac', date: '2026-03-06', time: '10:00', availableSlots: 3 },
  { id: 'r-61', driverId: 'driver-2', driverName: 'Ana Jovanović', driverVerified: true, from: 'Niš', to: 'Vranje', date: '2026-03-06', time: '13:00', availableSlots: 2 },
  { id: 'r-62', driverId: 'driver-10', driverName: 'Tamara Milošević', driverVerified: true, from: 'Užice', to: 'Valjevo', date: '2026-03-06', time: '08:30', availableSlots: 2 },
  { id: 'r-63', driverId: 'driver-4', driverName: 'Jelena Đorđević', from: 'Zrenjanin', to: 'Beograd', date: '2026-03-06', time: '11:00', availableSlots: 3 },
  { id: 'r-64', driverId: 'driver-9', driverName: 'Aleksandar Pavlović', driverVerified: true, from: 'Požarevac', to: 'Smederevo', date: '2026-03-06', time: '14:30', availableSlots: 2 },
  // === MART 7 ===
  { id: 'r-65', driverId: 'driver-8', driverName: 'Ivana Popović', from: 'Beograd', to: 'Zrenjanin', date: '2026-03-07', time: '08:00', availableSlots: 2 },
  { id: 'r-66', driverId: 'driver-2', driverName: 'Ana Jovanović', driverVerified: true, from: 'Beograd', to: 'Kragujevac', date: '2026-03-07', time: '11:30', availableSlots: 3 },
  { id: 'r-67', driverId: 'driver-7', driverName: 'Đorđe Milanović', driverVerified: true, from: 'Beograd', to: 'Kraljevo', date: '2026-03-07', time: '06:30', availableSlots: 4 },
  { id: 'r-68', driverId: 'driver-3', driverName: 'Stefan Nikolić', driverVerified: true, from: 'Kragujevac', to: 'Niš', date: '2026-03-07', time: '09:00', availableSlots: 2 },
  { id: 'r-69', driverId: 'driver-6', driverName: 'Milica Ilić', driverVerified: true, from: 'Čačak', to: 'Užice', date: '2026-03-07', time: '10:00', availableSlots: 2 },
  { id: 'r-70', driverId: 'driver-1', driverName: 'Marko Petrović', driverVerified: true, from: 'Novi Sad', to: 'Sombor', date: '2026-03-07', time: '14:00', availableSlots: 3 },
  { id: 'r-71', driverId: 'driver-5', driverName: 'Nikola Stojanović', driverVerified: true, from: 'Subotica', to: 'Novi Sad', date: '2026-03-07', time: '16:00', availableSlots: 5 },
  { id: 'r-72', driverId: 'driver-10', driverName: 'Tamara Milošević', driverVerified: true, from: 'Leskovac', to: 'Niš', date: '2026-03-07', time: '07:00', availableSlots: 2 },
  // === MART 8 ===
  { id: 'r-73', driverId: 'driver-1', driverName: 'Marko Petrović', driverVerified: true, from: 'Beograd', to: 'Novi Sad', date: '2026-03-08', time: '07:00', availableSlots: 5 },
  { id: 'r-74', driverId: 'driver-5', driverName: 'Nikola Stojanović', driverVerified: true, from: 'Subotica', to: 'Novi Sad', date: '2026-03-08', time: '15:00', availableSlots: 2 },
  { id: 'r-75', driverId: 'driver-3', driverName: 'Stefan Nikolić', driverVerified: true, from: 'Beograd', to: 'Čačak', date: '2026-03-08', time: '08:00', availableSlots: 3 },
  { id: 'r-76', driverId: 'driver-9', driverName: 'Aleksandar Pavlović', driverVerified: true, from: 'Beograd', to: 'Šabac', date: '2026-03-08', time: '10:00', availableSlots: 4 },
  { id: 'r-77', driverId: 'driver-2', driverName: 'Ana Jovanović', driverVerified: true, from: 'Pirot', to: 'Niš', date: '2026-03-08', time: '09:00', availableSlots: 2 },
  { id: 'r-78', driverId: 'driver-7', driverName: 'Đorđe Milanović', driverVerified: true, from: 'Kraljevo', to: 'Čačak', date: '2026-03-08', time: '12:00', availableSlots: 3 },
  { id: 'r-79', driverId: 'driver-4', driverName: 'Jelena Đorđević', from: 'Novi Sad', to: 'Beograd', date: '2026-03-08', time: '06:00', availableSlots: 3 },
  { id: 'r-80', driverId: 'driver-6', driverName: 'Milica Ilić', driverVerified: true, from: 'Beograd', to: 'Kruševac', date: '2026-03-08', time: '11:00', availableSlots: 2 },
  // === MART 13 ===
  { id: 'r-81', driverId: 'driver-1', driverName: 'Marko Petrović', driverVerified: true, from: 'Beograd', to: 'Novi Sad', date: '2026-03-13', time: '07:00', availableSlots: 4 },
  { id: 'r-82', driverId: 'driver-3', driverName: 'Stefan Nikolić', driverVerified: true, from: 'Beograd', to: 'Niš', date: '2026-03-13', time: '06:30', availableSlots: 3 },
  { id: 'r-83', driverId: 'driver-5', driverName: 'Nikola Stojanović', driverVerified: true, from: 'Beograd', to: 'Subotica', date: '2026-03-13', time: '08:00', availableSlots: 5 },
  { id: 'r-84', driverId: 'driver-7', driverName: 'Đorđe Milanović', driverVerified: true, from: 'Beograd', to: 'Kraljevo', date: '2026-03-13', time: '09:00', availableSlots: 3 },
  { id: 'r-85', driverId: 'driver-9', driverName: 'Aleksandar Pavlović', driverVerified: true, from: 'Beograd', to: 'Valjevo', date: '2026-03-13', time: '10:00', availableSlots: 3 },
  { id: 'r-86', driverId: 'driver-6', driverName: 'Milica Ilić', driverVerified: true, from: 'Beograd', to: 'Čačak', date: '2026-03-13', time: '11:00', availableSlots: 2 },
  { id: 'r-87', driverId: 'driver-10', driverName: 'Tamara Milošević', driverVerified: true, from: 'Beograd', to: 'Užice', date: '2026-03-13', time: '07:30', availableSlots: 2 },
  { id: 'r-88', driverId: 'driver-2', driverName: 'Ana Jovanović', driverVerified: true, from: 'Niš', to: 'Leskovac', date: '2026-03-13', time: '13:00', availableSlots: 2 },
  { id: 'r-89', driverId: 'driver-4', driverName: 'Jelena Đorđević', from: 'Novi Sad', to: 'Zrenjanin', date: '2026-03-13', time: '14:00', availableSlots: 3 },
  { id: 'r-90', driverId: 'driver-8', driverName: 'Ivana Popović', from: 'Kragujevac', to: 'Čačak', date: '2026-03-13', time: '12:00', availableSlots: 1 },
  { id: 'r-91', driverId: 'driver-1', driverName: 'Marko Petrović', driverVerified: true, from: 'Smederevo', to: 'Požarevac', date: '2026-03-13', time: '15:00', availableSlots: 3 },
  { id: 'r-92', driverId: 'driver-5', driverName: 'Nikola Stojanović', driverVerified: true, from: 'Kruševac', to: 'Niš', date: '2026-03-13', time: '16:00', availableSlots: 2 },
  { id: 'r-93', driverId: 'driver-3', driverName: 'Stefan Nikolić', driverVerified: true, from: 'Pirot', to: 'Niš', date: '2026-03-13', time: '08:30', availableSlots: 2 },
  { id: 'r-94', driverId: 'driver-7', driverName: 'Đorđe Milanović', driverVerified: true, from: 'Novi Pazar', to: 'Kraljevo', date: '2026-03-13', time: '10:30', availableSlots: 2 },
  // === MART 14 ===
  { id: 'r-95', driverId: 'driver-2', driverName: 'Ana Jovanović', driverVerified: true, from: 'Beograd', to: 'Niš', date: '2026-03-14', time: '06:00', availableSlots: 3 },
  { id: 'r-96', driverId: 'driver-1', driverName: 'Marko Petrović', driverVerified: true, from: 'Beograd', to: 'Novi Sad', date: '2026-03-14', time: '08:00', availableSlots: 4 },
  { id: 'r-97', driverId: 'driver-5', driverName: 'Nikola Stojanović', driverVerified: true, from: 'Subotica', to: 'Beograd', date: '2026-03-14', time: '07:00', availableSlots: 5 },
  { id: 'r-98', driverId: 'driver-3', driverName: 'Stefan Nikolić', driverVerified: true, from: 'Beograd', to: 'Kragujevac', date: '2026-03-14', time: '09:30', availableSlots: 2 },
  { id: 'r-99', driverId: 'driver-6', driverName: 'Milica Ilić', driverVerified: true, from: 'Čačak', to: 'Beograd', date: '2026-03-14', time: '07:30', availableSlots: 2 },
  { id: 'r-100', driverId: 'driver-10', driverName: 'Tamara Milošević', driverVerified: true, from: 'Užice', to: 'Beograd', date: '2026-03-14', time: '06:30', availableSlots: 2 },
  { id: 'r-101', driverId: 'driver-9', driverName: 'Aleksandar Pavlović', driverVerified: true, from: 'Šabac', to: 'Beograd', date: '2026-03-14', time: '10:00', availableSlots: 3 },
  { id: 'r-102', driverId: 'driver-7', driverName: 'Đorđe Milanović', driverVerified: true, from: 'Kraljevo', to: 'Niš', date: '2026-03-14', time: '11:00', availableSlots: 3 },
  { id: 'r-103', driverId: 'driver-4', driverName: 'Jelena Đorđević', from: 'Novi Sad', to: 'Subotica', date: '2026-03-14', time: '13:00', availableSlots: 2 },
  { id: 'r-104', driverId: 'driver-8', driverName: 'Ivana Popović', from: 'Pančevo', to: 'Smederevo', date: '2026-03-14', time: '12:00', availableSlots: 1 },
  { id: 'r-105', driverId: 'driver-2', driverName: 'Ana Jovanović', driverVerified: true, from: 'Vranje', to: 'Niš', date: '2026-03-14', time: '14:00', availableSlots: 2 },
  { id: 'r-106', driverId: 'driver-1', driverName: 'Marko Petrović', driverVerified: true, from: 'Sombor', to: 'Novi Sad', date: '2026-03-14', time: '15:30', availableSlots: 3 },
  { id: 'r-107', driverId: 'driver-5', driverName: 'Nikola Stojanović', driverVerified: true, from: 'Beograd', to: 'Kruševac', date: '2026-03-14', time: '16:00', availableSlots: 3 },
  { id: 'r-108', driverId: 'driver-3', driverName: 'Stefan Nikolić', driverVerified: true, from: 'Leskovac', to: 'Vranje', date: '2026-03-14', time: '08:00', availableSlots: 2 },
  // === MART 15 ===
  { id: 'r-109', driverId: 'driver-1', driverName: 'Marko Petrović', driverVerified: true, from: 'Beograd', to: 'Subotica', date: '2026-03-15', time: '07:00', availableSlots: 4 },
  { id: 'r-110', driverId: 'driver-3', driverName: 'Stefan Nikolić', driverVerified: true, from: 'Beograd', to: 'Niš', date: '2026-03-15', time: '06:00', availableSlots: 3 },
  { id: 'r-111', driverId: 'driver-5', driverName: 'Nikola Stojanović', driverVerified: true, from: 'Beograd', to: 'Kragujevac', date: '2026-03-15', time: '09:00', availableSlots: 3 },
  { id: 'r-112', driverId: 'driver-7', driverName: 'Đorđe Milanović', driverVerified: true, from: 'Beograd', to: 'Kraljevo', date: '2026-03-15', time: '08:30', availableSlots: 4 },
  { id: 'r-113', driverId: 'driver-6', driverName: 'Milica Ilić', driverVerified: true, from: 'Beograd', to: 'Čačak', date: '2026-03-15', time: '10:00', availableSlots: 2 },
  { id: 'r-114', driverId: 'driver-10', driverName: 'Tamara Milošević', driverVerified: true, from: 'Beograd', to: 'Užice', date: '2026-03-15', time: '11:00', availableSlots: 2 },
  { id: 'r-115', driverId: 'driver-9', driverName: 'Aleksandar Pavlović', driverVerified: true, from: 'Beograd', to: 'Valjevo', date: '2026-03-15', time: '12:00', availableSlots: 3 },
  { id: 'r-116', driverId: 'driver-2', driverName: 'Ana Jovanović', driverVerified: true, from: 'Niš', to: 'Pirot', date: '2026-03-15', time: '13:00', availableSlots: 2 },
  { id: 'r-117', driverId: 'driver-4', driverName: 'Jelena Đorđević', from: 'Novi Sad', to: 'Beograd', date: '2026-03-15', time: '07:30', availableSlots: 3 },
  { id: 'r-118', driverId: 'driver-8', driverName: 'Ivana Popović', from: 'Zrenjanin', to: 'Novi Sad', date: '2026-03-15', time: '14:00', availableSlots: 1 },
  { id: 'r-119', driverId: 'driver-1', driverName: 'Marko Petrović', driverVerified: true, from: 'Požarevac', to: 'Beograd', date: '2026-03-15', time: '15:00', availableSlots: 3 },
  { id: 'r-120', driverId: 'driver-5', driverName: 'Nikola Stojanović', driverVerified: true, from: 'Novi Pazar', to: 'Kraljevo', date: '2026-03-15', time: '09:30', availableSlots: 2 },
  { id: 'r-121', driverId: 'driver-7', driverName: 'Đorđe Milanović', driverVerified: true, from: 'Kruševac', to: 'Kragujevac', date: '2026-03-15', time: '16:00', availableSlots: 2 },
  { id: 'r-122', driverId: 'driver-6', driverName: 'Milica Ilić', driverVerified: true, from: 'Smederevo', to: 'Požarevac', date: '2026-03-15', time: '08:00', availableSlots: 2 },
  // === MART 16 ===
  { id: 'r-123', driverId: 'driver-2', driverName: 'Ana Jovanović', driverVerified: true, from: 'Beograd', to: 'Niš', date: '2026-03-16', time: '06:00', availableSlots: 3 },
  { id: 'r-124', driverId: 'driver-1', driverName: 'Marko Petrović', driverVerified: true, from: 'Beograd', to: 'Novi Sad', date: '2026-03-16', time: '07:00', availableSlots: 5 },
  { id: 'r-125', driverId: 'driver-5', driverName: 'Nikola Stojanović', driverVerified: true, from: 'Beograd', to: 'Subotica', date: '2026-03-16', time: '08:00', availableSlots: 4 },
  { id: 'r-126', driverId: 'driver-3', driverName: 'Stefan Nikolić', driverVerified: true, from: 'Beograd', to: 'Kragujevac', date: '2026-03-16', time: '09:00', availableSlots: 2 },
  { id: 'r-127', driverId: 'driver-7', driverName: 'Đorđe Milanović', driverVerified: true, from: 'Beograd', to: 'Kraljevo', date: '2026-03-16', time: '10:00', availableSlots: 3 },
  { id: 'r-128', driverId: 'driver-10', driverName: 'Tamara Milošević', driverVerified: true, from: 'Beograd', to: 'Užice', date: '2026-03-16', time: '07:30', availableSlots: 2 },
  { id: 'r-129', driverId: 'driver-6', driverName: 'Milica Ilić', driverVerified: true, from: 'Čačak', to: 'Kraljevo', date: '2026-03-16', time: '11:00', availableSlots: 2 },
  { id: 'r-130', driverId: 'driver-9', driverName: 'Aleksandar Pavlović', driverVerified: true, from: 'Valjevo', to: 'Šabac', date: '2026-03-16', time: '12:00', availableSlots: 3 },
  { id: 'r-131', driverId: 'driver-4', driverName: 'Jelena Đorđević', from: 'Subotica', to: 'Sombor', date: '2026-03-16', time: '13:00', availableSlots: 2 },
  { id: 'r-132', driverId: 'driver-8', driverName: 'Ivana Popović', from: 'Pančevo', to: 'Zrenjanin', date: '2026-03-16', time: '14:00', availableSlots: 1 },
  { id: 'r-133', driverId: 'driver-2', driverName: 'Ana Jovanović', driverVerified: true, from: 'Niš', to: 'Vranje', date: '2026-03-16', time: '15:00', availableSlots: 2 },
  { id: 'r-134', driverId: 'driver-3', driverName: 'Stefan Nikolić', driverVerified: true, from: 'Niš', to: 'Leskovac', date: '2026-03-16', time: '08:30', availableSlots: 2 },
  { id: 'r-135', driverId: 'driver-5', driverName: 'Nikola Stojanović', driverVerified: true, from: 'Kruševac', to: 'Kraljevo', date: '2026-03-16', time: '16:00', availableSlots: 3 },
  { id: 'r-136', driverId: 'driver-1', driverName: 'Marko Petrović', driverVerified: true, from: 'Smederevo', to: 'Beograd', date: '2026-03-16', time: '06:30', availableSlots: 4 },
];

export const DEMO_REVIEWS: Review[] = [
  { id: 'rev-1', fromUserId: 'driver-1', fromUserName: 'Marko Petrović', toUserId: 'driver-2', toUserName: 'Ana Jovanović', rating: 5, comment: 'Odlična komunikacija i brza isporuka! Paket stigao u savršenom stanju.', type: 'posiljalac', date: '2026-02-20' },
  { id: 'rev-2', fromUserId: 'driver-3', fromUserName: 'Stefan Nikolić', toUserId: 'driver-1', toUserName: 'Marko Petrović', rating: 5, comment: 'Pouzdan vozač, preporučujem svima. Uvek tačan i ljubazan.', type: 'vozac', date: '2026-02-18' },
  { id: 'rev-3', fromUserId: 'driver-4', fromUserName: 'Jelena Đorđević', toUserId: 'driver-3', toUserName: 'Stefan Nikolić', rating: 5, comment: 'Sve je stiglo u savršenom stanju. Hvala puno!', type: 'vozac', date: '2026-02-15' },
  { id: 'rev-4', fromUserId: 'driver-2', fromUserName: 'Ana Jovanović', toUserId: 'driver-1', toUserName: 'Marko Petrović', rating: 4, comment: 'Sve je bilo u redu, samo malo kašnjenja ali paket je bio bezbedan.', type: 'vozac', date: '2026-02-12' },
  { id: 'rev-5', fromUserId: 'driver-5', fromUserName: 'Nikola Stojanović', toUserId: 'driver-3', toUserName: 'Stefan Nikolić', rating: 5, comment: 'Profesionalan pristup, kao da šaljete kurirskom službom. Top!', type: 'vozac', date: '2026-02-10' },
  { id: 'rev-6', fromUserId: 'driver-1', fromUserName: 'Marko Petrović', toUserId: 'driver-5', toUserName: 'Nikola Stojanović', rating: 5, comment: 'Brz, efikasan, odgovoran. Sve pohvale za Nikolu!', type: 'vozac', date: '2026-02-08' },
  { id: 'rev-7', fromUserId: 'driver-6', fromUserName: 'Milica Ilić', toUserId: 'driver-7', toUserName: 'Đorđe Milanović', rating: 5, comment: 'Neverovatno brza dostava. Paket je stigao istog dana!', type: 'vozac', date: '2026-02-05' },
  { id: 'rev-8', fromUserId: 'driver-7', fromUserName: 'Đorđe Milanović', toUserId: 'driver-6', toUserName: 'Milica Ilić', rating: 4, comment: 'Prijatna osoba, lako smo se dogovorili oko detalja.', type: 'posiljalac', date: '2026-02-03' },
  { id: 'rev-9', fromUserId: 'driver-8', fromUserName: 'Ivana Popović', toUserId: 'driver-5', toUserName: 'Nikola Stojanović', rating: 5, comment: 'Iskusan vozač, paket zapakovan bolje nego što sam ja poslala!', type: 'vozac', date: '2026-01-28' },
  { id: 'rev-10', fromUserId: 'driver-9', fromUserName: 'Aleksandar Pavlović', toUserId: 'driver-1', toUserName: 'Marko Petrović', rating: 5, comment: 'Marko je uvek spreman da pomogne. Odlična usluga.', type: 'vozac', date: '2026-01-25' },
  { id: 'rev-11', fromUserId: 'driver-10', fromUserName: 'Tamara Milošević', toUserId: 'driver-2', toUserName: 'Ana Jovanović', rating: 4, comment: 'Sve je proteklo kako treba. Komunikacija na visokom nivou.', type: 'posiljalac', date: '2026-01-22' },
  { id: 'rev-12', fromUserId: 'driver-3', fromUserName: 'Stefan Nikolić', toUserId: 'driver-7', toUserName: 'Đorđe Milanović', rating: 5, comment: 'Đorđe je pravi profesionalac. Preporučujem bez rezerve.', type: 'vozac', date: '2026-01-20' },
  { id: 'rev-13', fromUserId: 'driver-5', fromUserName: 'Nikola Stojanović', toUserId: 'driver-9', toUserName: 'Aleksandar Pavlović', rating: 5, comment: 'Iskustvo se vidi! Paket je bio na destinaciji pre vremena.', type: 'vozac', date: '2026-01-18' },
  { id: 'rev-14', fromUserId: 'driver-4', fromUserName: 'Jelena Đorđević', toUserId: 'driver-10', toUserName: 'Tamara Milošević', rating: 5, comment: 'Tamara je super! Komunikativna i pouzdana.', type: 'vozac', date: '2026-01-15' },
  { id: 'rev-15', fromUserId: 'driver-2', fromUserName: 'Ana Jovanović', toUserId: 'driver-6', toUserName: 'Milica Ilić', rating: 4, comment: 'Dobra saradnja, sve je prošlo bez problema.', type: 'posiljalac', date: '2026-01-12' },
  { id: 'rev-16', fromUserId: 'driver-1', fromUserName: 'Marko Petrović', toUserId: 'driver-4', toUserName: 'Jelena Đorđević', rating: 4, comment: 'Jelena je prijatna osoba, slanje je bilo lako i brzo.', type: 'posiljalac', date: '2026-01-10' },
  { id: 'rev-17', fromUserId: 'driver-7', fromUserName: 'Đorđe Milanović', toUserId: 'driver-5', toUserName: 'Nikola Stojanović', rating: 5, comment: 'Nikola je kralj dostave! Apsolutno savršeno iskustvo.', type: 'vozac', date: '2026-01-08' },
  { id: 'rev-18', fromUserId: 'driver-9', fromUserName: 'Aleksandar Pavlović', toUserId: 'driver-3', toUserName: 'Stefan Nikolić', rating: 5, comment: 'Stefan je pouzdaniji od kurirske službe. Svaka čast!', type: 'vozac', date: '2026-01-05' },
  { id: 'rev-19', fromUserId: 'driver-10', fromUserName: 'Tamara Milošević', toUserId: 'driver-7', toUserName: 'Đorđe Milanović', rating: 5, comment: 'Prebrza dostava i odlična komunikacija. Vrh!', type: 'vozac', date: '2026-01-03' },
  { id: 'rev-20', fromUserId: 'driver-6', fromUserName: 'Milica Ilić', toUserId: 'driver-1', toUserName: 'Marko Petrović', rating: 5, comment: 'Marko je uvek tačan i pouzdan. Definitivno ponovo!', type: 'vozac', date: '2026-01-01' },
];
